version: '2'

services:
  organilab_database:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=0rg4n1l4b
      - POSTGRES_USER=organilab_user
      - POSTGRES_DB=organilab

# Organilab
  organilab:
    hostname: organilab.org
    image: organilab
    command: gunicorn organilab.wsgi:application --bind 0.0.0.0:80 --workers 1
    depends_on:
      - organilab_database
    environment:
      - ALLOWED_HOSTS=organilab.org
      - DBNAME=organilab
      - DBUSER=organilab_user
      - DBPASSWORD=0rg4n1l4b
      - DBHOST=organilab_database
      - DBPORT=5432
      - BROKER_URL='amqp://myuser:mypassword@organilab_rabbitmq:5672/myvhost'
      - CELERY_RESULT_BACKEND='amqp://myuser:mypassword@organilab_rabbitmq:5672/myvhost'
      - VIRTUAL_HOST=organilab.org
    volumes:
        - ./static:/organilab/static
        - ./media:/organilab/media

  nginx:
    image: nginx:latest
    container_name: ng01
    depends_on:
      - organilab
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
      - ./media:/media
    ports:
      - "8123:80"


# RABBIT MQ para celery
  organilab_rabbitmq:
    hostname: rabbitmq.organilab.org
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
      - RABBITMQ_DEFAULT_VHOST=myvhost

